// export interface IClient {
//     id: string;
//     referenceName: string;
//     officeName: string;
//     clientName: string;
//     dateOfBirth: string;
//     passportNumber: string;
//     visaNumber: string;
//     idNumber: string;
//     kofeelNumber: string;
//     medicalDate: string;
//     medicalExpireDate: string;
//     medicalStatus: boolean;
//     clientNumber: string;
//     policeClearance: boolean;
//     MofaStatus: boolean;
//     mofaDate: string | null;
//     visaFingerDate: string | null;
//     manPowerFingerDate: string | null;
//     trainingStatus: boolean;
//     courierDate: string | null;
//     TakammolCertificate: boolean;
//     visaStatus: boolean;
//     manPowerStatus: boolean;
//     passportDelivery: string | null;
//     ticketDate: string;
//     scanCopy: string;
//     notes?: string;
//     status: "ACTIVE" | "PENDING" | "CANCELLED" | "COMPLETED";
//     updatedBy: string | null;
//     deletedBy: string | null;
//     isDeleted: boolean;
//     createdAt: string;
//     updatedAt: string;
// }

export interface IClient {
    client: {
        id: string;
        referenceName: string;
        officeName: string;
        clientName: string;
        dateOfBirth: string;
        passportNumber: string;
        visaNumber: string;
        idNumber: string;
        koffileNumber: string;
        kofeelNumber: string;
        medicalDate: string;
        medicalExpireDate: string;
        medicalStatus: boolean;
        clientNumber: string;
        policeClearance: boolean;
        MofaStatus: boolean;
        mofaDate: string | null;
        visaFingerDate: string | null;
        manPowerFingerDate: string | null;
        trainingStatus: boolean;
        courierDate: string | null;
        TakammolCertificate: boolean;
        visaStatus: boolean;
        manPowerStatus: boolean;
        passportDelivery: string | null;
        ticketDate: string;
        scanCopy: string;
        notes?: string;
        status: "ACTIVE" | "PENDING" | "CANCELLED" | "COMPLETED";
        updatedBy: string | null;
        deletedBy: string | null;
        isDeleted: boolean;
        createdAt: string;
        updatedAt: string;
    };
}
